name: halalin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  akar_icons_flutter: ^1.1.11
  animated_splash_screen: ^1.3.0
  bottom_navy_bar: ^6.0.0
  camera: ^0.10.0+4
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_tesseract_ocr: ^0.4.20
  get: 4.6.5
  google_mlkit_commons: ^0.2.0
  google_mlkit_text_recognition:
    git:
      url: https://github.com/Thoriq-ha/google_mlkit_text_recognition.git
      ref: main
  iconsax: ^0.0.8
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  sliding_up_panel: ^2.0.0+1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/launcherfg.png
  adaptive_icon_background: assets/images/launcherbg.png
  adaptive_icon_foreground: assets/images/launcherfg.png

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/poppins/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/ornamentTop.png
    - assets/images/ornamentBot.png
    - assets/images/ornamentAppbarLeft.png
    - assets/images/ornamentAppbarRight.png
    - assets/images/ornamentAboutLeft.png
    - assets/images/ornamentAboutRight.png
    - assets/images/headline.png
    - assets/images/food.png
    - assets/images/pp/dickyPP.png
    - assets/images/pp/krisnaPP.png
    - assets/images/pp/sadadPP.png
    - assets/images/pp/thoriqPP.png
    - assets/images/launcherbg.png
    - assets/images/launcherfg.png
    - assets/
    - assets/dataset/
    - assets/tessdata/
